//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndividualPartB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment : IEntity
    {
        public Assignment(string title, string description, DateTime? subDateTime, int? oralMark, int? totalMark, int? courseID)
        {
            Title = title;
            Description = description;
            SubDateTime = subDateTime;
            OralMark = oralMark;
            TotalMark = totalMark;
            CourseID = courseID;
        }

        public Assignment()
        {

        }

        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> SubDateTime { get; set; }
        public Nullable<int> OralMark { get; set; }
        public Nullable<int> TotalMark { get; set; }
        public Nullable<int> CourseID { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
